const articles = [
  {
    id: 0,
    name: "Combattant mâle",
    url: "./assets/img/poissons/betta.jpg",
    price: 9.69,
    promo: true,
    qte: 10,
    description:
      "Petit poisson d’eau douce arborant des nageoires majestueuses aux couleurs chatoyantes, le combattant vit seul. Un aquarium de 15L minimum, très bien planté sera un environnement parfait pour ce petit poisson. le Betta est Le combattant est un poisson à tendance vermivore et insectivore.",
  },
  {
    id: 1,
    name: "Colisa Lalia",
    url: "./assets/img/poissons/gourami.jpg",
    price: 9.95,
    promo: false,
    qte: 5,
    description: "Poisson d'eau douce mesurant entre 4 et 5 cm adulte, il présente un corps élancé, ovoïde et légèrement comprimé latéralement. Ce petit poisson vit en couple. Son aquarium de 50L minimum doit être bien planté avec des plantes de surface et posséder de nombreuses cachettes. Son régime alimentaire est omnivore à tendance insectivore.",
  },
  {
    id: 2,
    name: "Nez Rouge",
    url: "./assets/img/poissons/nezrouge.jpg",
    price: 5.79,
    promo: true,
    qte: 7,
    description: "Le Nez rouge est un petit poisson d’environ 5 cm adulte. Il vit en banc de 10 individus minimum. Très bon nageur, son aquarium doit avoir une longueur de 100cm minimum, il apprécie une végétation dense avec des plantes de surface pour tamiser la lumière. Omnivore, il ne présente pas de difficulté pour la nourriture.",
  },
  {
    id: 3,
    name: "Microrasbora Kubotai",
    url: "./assets/img/poissons/kubotai.jpg",
    price: 8.17,
    promo: true,
    qte: 3,
    description: "Le Microrasbora kubotai mesure environ 2cm adulte. En tant que poisson de banc, celui-ci doit vivre en groupe de 10 individus minimum. En aquarium spécifique, ce petit poisson peut être maintenu dans un volume de 35L. Omnivore, il apprécie particulièrement les proies vivantes ou congelées comme les daphnies, cyclopes, vers de vase, artemias, …",
  },
  {
    id: 4,
    name: "Pangio Kuhli",
    url: "./assets/img/poissons/kuhli.jpg",
    price: 6.28,
    promo: true,
    qte: 8,
    description: "Poisson d’eau douce mesurant jusqu’à 10 cm adulte. Le kulhi est grégaire, son banc doit être composé de 5 individus minimum. Son aquarium de 120L minimum pour un groupe de 5 individus sera bien planté afin de lui offrir de nombreuses cachettes. Omnivore, il apprécie les vers de vase et demande un apport régulier de végétaux soit sous forme de pastilles pour poissons de fond, soit de légumes.",
  },
  {
    id: 5,
    name: "Killi de Gardner",
    url: "./assets/img/poissons/killi.jpg",
    price: 9.08,
    promo: true,
    qte: 3,
    description: "Le Fundulopanchax gardneri est un petit poisson très coloré qui mesure environ 6cm adulte. Ce poisson doit vivre en couple ou en trio. Son aquarium d’un volume de 10L minimum pour un trio sera constitué d’un substrat sombre, d’une végétation dense et de plantes de surface afin de tamiser la lumière. Le Fundulopanchax gardneri est carnivore, il apprécie particulièrement les vers de vase, artémias, daphnies, …",
  },
  {
    id: 6,
    name: "Neocaridina heteropoda - Blue Fire",
    url: "./assets/img/poissons/crevette.jpg",
    price: 6.15,
    promo: true,
    qte: 7,
    description: "La Blue Fire présente un corps entièrement bleu, parsemé de petits points noirs. Une variété sublime, mais pas toujours facile à trouver, d'autant plus qu'entre 30 et 40% des individus peuvent tirer sur le brun ou le gris. Les oeufs ont une couleur bleutée ou grisâtre. Sa maintenance et sa reproduction est similaire aux autre Neocaridina Heteropoda.",
  },
];

export default articles;
